[package]
name = "finddups"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
blake2 = "0.10"
base64ct = { version = "1.5", features = ["alloc"] }
jwalk = "0.6"
rayon = "1.5"
